  IF (IN_LIMITPLANT='T') THEN
    BEGIN
      BEGIN
         SELECT PLANTKEY
           INTO V_OPKEY
           FROM RELIEFD
          WHERE UNIQUEKEY=IN_RVKEY
          AND TENANTKEY=V_TENANTKEY;
      EXCEPTION
      WHEN NO_DATA_FOUND THEN
        V_OPKEY:='';
      END;

      IF (V_OPKEY IS NOT NULL) THEN
        V_WHERESQL:=V_WHERESQL || ' AND TENANTKEY =''' || V_TENANTKEY || ''' AND PLANTKEY =''' || V_OPKEY || '''';
      ELSE
        V_WHERESQL:=V_WHERESQL || ' AND TENANTKEY =''' || V_TENANTKEY || ''' AND PLANTKEY =''' || IN_PLANTKEY || '''';
      END IF;
    END;
  ELSIF (IN_LIMITOWNER='T') THEN
    BEGIN
      BEGIN
         SELECT OWNERKEY
           INTO V_OPKEY
           FROM RELIEFD
          WHERE UNIQUEKEY=IN_RVKEY
          AND TENANTKEY=V_TENANTKEY;
      EXCEPTION
      WHEN NO_DATA_FOUND THEN
        V_OPKEY:='';
      END;

      IF (V_OPKEY IS NOT NULL) THEN
        V_WHERESQL:=V_WHERESQL || ' AND TENANTKEY =''' || V_TENANTKEY || ''' AND  OWNERKEY =''' || V_OPKEY || '''';
      ELSE
        V_WHERESQL:=V_WHERESQL || ' AND  TENANTKEY =''' || V_TENANTKEY || ''' AND OWNERKEY =''' || IN_OWNERKEY || '''';
      END IF;
    END;
  END IF;

  IF (IN_NOBLANKSPRING='T') THEN
    BEGIN
      V_WHERESQL:=V_WHERESQL || ' AND NVL(SPRINGNUMBER, '''') IS NOT NULL';
    END;
  END IF;

  IF (V_SPRINGNUMBER IS NOT NULL) THEN
    BEGIN
      V_WHERESQL:=V_WHERESQL || ' AND instr(SPRINGNUMBER, '''||V_SPRINGNUMBER||''') >0 ';
    END;
  END IF;

  IF (IN_SETVALUE>0) THEN
    BEGIN
      V_INTFROM:=IN_MIDDLEVALUE-IN_SETVALUE;
      V_INTTO:=IN_MIDDLEVALUE+IN_SETVALUE;
      V_WHERESQL:=V_WHERESQL || ' AND (SETPRESSURE BETWEEN ' || V_INTFROM || ' AND ' || V_INTTO ||
      ' OR COLDDIFFSET BETWEEN ' || V_INTFROM || ' AND ' || V_INTTO || ')';
    END;
  END IF;